version: "3.5"

services:
  nginx:
    image: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - 8080:80
    networks:
      - climtem-net

  climtem-back:
    image: climtem-back
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - database
    networks:
      - climtem-net

  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: $PSQL_DB
      POSTGRES_USER: $PSQL_USER
      POSTGRES_PASSWORD: $PSQL_PASSWORD
    volumes:
      - ./Create_Table_Ecommerce.sql:/docker-entrypoint-initdb.d/Create_Table_Ecommerce.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - climtem-net

networks:
  climtem-net:
    name: climtem-net
    driver: bridge

volumes:
  pgdata:
    driver: local